### PR TITLE
allow edit and delete of notes

### PR DESCRIPTION
**Pull request by stweise**
This is a proposal to fix issue #33 #30 

notes are selected in list using Enter, an editing window is presented
* deleting entire text will delete note
* altering text will alter note (it will however still contain the date information as rendered by the note class)

i would love to discuss futher changes to the note class to get rid of the date issue

### CODE REVIEW

**Comment by stweise** [comment]
I do not have permissions to push to your repository. That is why is sent you the pull request so that you could do that. I also am no allowed to merge the request myself: "Only those with write access to this repository can merge pull requests."

**Comment by stweise** [comment]
This now also includes drawing of column ends.

**Comment by stweise** [comment]
Saving is already performed upon calling Quit(), removing double invocation, when calling "Quit" on menu.

**Comment by stweise** [comment]
@gtaubman could you add me as a collaborator so that i can push these changes?

**Comment by stweise** [comment]
This now also fixes #32

**Comment by gtaubman** [comment]
Hi Steffen,

I'm so sorry for the year long silence!  I must not have had notifications set up for this thread and don't sign into the github UI very often!

I've sent an invite adding you as a collaborator to the project.  I see a "Merge pull request" button here but I'll wait for you to accept the collaboration (if you want) and you can merge it yourself :)

Thanks so much for taking it over!

**Pull request merged**
